# -*- coding: utf-8 -*-
"""MeuPythonEscolhaSorteio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xxZjFs5mJA3AN7al2Kn47yowmtjsEIwR
"""

import random
import string

escolha = int(input('Escolha o tipo de sorteio: Digite (1)-Para numeros ou (2)-Para letras ou (0)-Para Zero ou Um\n'))

if escolha == 2:
  letraaleatoria = random.choice(string.ascii_uppercase)
  print('A letra sorteada foi: {}'.format(letraaleatoria))
elif escolha == 0:
  zeroouum = random.random()
  print('Zero ou Um:{:.0f}'.format(zeroouum))
else:
  quantidade = int(input('Qual quantidade de números para o sorteiro?'))
  numeroaleatorio = random.randrange(1, quantidade)
  print('O número sorteado foi: {}'.format(numeroaleatorio))